mongodb:
  image:
    registry: docker.io
    repository: bitnamilegacy/mongodb
    tag: latest
  arbiter:
    image:
      registry: docker.io
      repository: bitnamilegacy/mongodb
      tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  persistence:
    size: 5Gi
    storageClass: gp2

global:
  security:
    allowInsecureImages: true
