image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: latest

global:
  security:
    allowInsecureImages: true

auth:
  username: orders
  password: orders
  database: orders

primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp2

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
