apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://charts.chaos-mesh.org
      chart: chaos-mesh
      targetRevision: 2.8.2
      helm:
        releaseName: chaos-mesh
        valueFiles:
          - $values/helm/chaos-mesh/values.yaml
    - repoURL: https://github.com/Alves0611/reliabilityos.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
