apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.19.0
      helm:
        releaseName: keda
        valueFiles:
          - $values/helm/keda/values.yaml
    - repoURL: https://github.com/Alves0611/reliabilityos.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
