apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://litmuschaos.github.io/litmus-helm
      chart: litmus
      targetRevision: 3.12.0
      helm:
        releaseName: litmus
        valueFiles:
          - $values/helm/litmus/values.yaml
    - repoURL: https://github.com/Alves0611/reliabilityos.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: litmus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
