apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: rabbitmq
      targetRevision: 15.1.5
      helm:
        releaseName: rabbitmq
        valueFiles:
          - $values/helm/rabbitmq/values.yaml
    - repoURL: https://github.com/Alves0611/reliabilityos.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: reliabilityos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
