replicaCount: 2

image:
  repository: 444065722670.dkr.ecr.us-east-1.amazonaws.com/reliabilityos/orders-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: orders.gabrielstudying.click

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  ORDERS_DATABASE_URL: "postgresql+asyncpg://orders:orders@postgresql.reliabilityos.svc.cluster.local:5432/orders"
  ORDERS_RABBITMQ_URL: "amqp://guest:guest@rabbitmq.reliabilityos.svc.cluster.local:5672//"
