configs:
  params:
    server.insecure: true
  repositories:
    bitnami:
      url: https://charts.bitnami.com/bitnami
      name: bitnami
      type: helm

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.gabrielstudying.click