configs:
  params:
    server.insecure: true
  repositories:
    bitnami:
      url: registry-1.docker.io/bitnamicharts
      name: bitnami
      type: helm
      enableOCI: "true"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.gabrielstudying.click