name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan-cluster:
    name: Plan Destroy Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/02-cluster
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: terraform/02-cluster
        run: terraform plan -destroy -no-color
        env:
          TF_VAR_github_token: ${{ secrets.ARGOCD_GITHUB_TOKEN }}

  destroy-cluster:
    name: Destroy Cluster
    needs: plan-cluster
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/02-cluster
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/02-cluster
        run: terraform destroy -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.ARGOCD_GITHUB_TOKEN }}

  plan-vpc:
    name: Plan Destroy VPC
    needs: destroy-cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/01-vpc
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: terraform/01-vpc
        run: terraform plan -destroy -no-color

  destroy-vpc:
    name: Destroy VPC
    needs: plan-vpc
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/01-vpc
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/01-vpc
        run: terraform destroy -auto-approve
